#!/usr/bin/env bash
# Bash script that will display information about subdomains

domain=$1
subdomain=$2

subdomains=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 1 ];
then
    for i in "${subdomains[@]}"
    do
        dig "$i"."$domain" | grep -A1 'ANSWER SECTION:' > "file"
        awk -v i="$i" 'NR == 2 {print "The subdomain "i" is a "$4" record and points to "$5}' file    
    done
else
    dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' > "file"
    awk -v i="$subdomain" 'NR == 2 {print "The subdomain "i" is a "$4" record and points to "$5}' file
fi
