#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo echo "ENABLED-=1" >> /etc/default/haproxy
sudo echo "frontend frontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 42903-web-01 54.236.45.115:80 check
        server 42903-web-02 100.26.252.171:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
