#!/usr/bin/env bash
# A Bash script
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back
backend http_back
        balance roundrobin
        server 42903-web-01 54.236.45.115:80 check
        server 42903-web-02 100.26.252.171:80 check
" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
